export const Jobs = [
	{ id: 1, name: "Application Developer", available: 12 },
	{ id: 2, name: "Cyber Security Analyst", available: 12 },
	{ id: 3, name: "Game Developer", available: 12 },
	{ id: 4, name: "Information System Manager", available: 12 },
	{ id: 5, name: "IT Consultant", available: 12 },
	{ id: 6, name: "Multimedia Programmer", available: 12 },
	{ id: 7, name: "Web Developer", available: 12 },
	{ id: 8, name: "Web Designer", available: 12 },
	{ id: 9, name: "Software Engineer", available: 12 },
	{ id: 10, name: "Digital Marketer", available: 12 },
];

export const JobsCategory = [
	{ id: 1, name: "HTML", value: "html" },
	{ id: 2, name: "CSS", value: "css" },
	{ id: 3, name: "JAVA", value: "java" },
	{ id: 4, name: "PHP", value: "php" },
	{ id: 5, name: "SQL", value: "sql" },
	{ id: 6, name: "C++", value: "c++" },
];

export const CreateJobs = [
	{
		id: 1,
		image: "test image",
		name: "Digital Marketer",
		author: "SaveNet inc",
		location: "London",
		amount: "$12,000",
		type: "Full Time",
		create_time: "1 hour ago",
	},
	{
		id: 2,
		image: "test image",
		name: "Application Developer",
		author: "SaveNet inc",
		location: "London",
		amount: "$12,000",
		type: "Full Time",
		create_time: "1 hour ago",
	},
	{
		id: 3,
		image: "test image",
		name: "Cyber Security Analyst",
		author: "SaveNet inc",
		location: "London",
		amount: "$12,000",
		type: "Full Time",
		create_time: "1 hour ago",
	},
	{
		id: 4,
		image: "test image",
		name: "Game Developer",
		author: "SaveNet inc",
		location: "London",
		amount: "$12,000",
		type: "Full Time",
		create_time: "1 hour ago",
	},
	{
		id: 5,
		image: "test image",
		name: "IT Consultant",
		author: "SaveNet inc",
		location: "London",
		amount: "$12,000",
		type: "Full Time",
		create_time: "1 hour ago",
	},
	{
		id: 6,
		image: "test image",
		name: "Information System Manager",
		author: "SaveNet inc",
		location: "London",
		amount: "$12,000",
		type: "Full Time",
		create_time: "1 hour ago",
	},
	{
		id: 7,
		image: "test image",
		name: "Multimedia Programmer",
		author: "SaveNet inc",
		location: "London",
		amount: "$12,000",
		type: "Full Time",
		create_time: "1 hour ago",
	},
	{
		id: 8,
		image: "test image",
		name: "Web Developer",
		author: "SaveNet inc",
		location: "London",
		amount: "$12,000",
		type: "Full Time",
		create_time: "1 hour ago",
	},
	{
		id: 9,
		image: "test image",
		name: "Web Designer",
		author: "SaveNet inc",
		location: "London",
		amount: "$12,000",
		type: "Full Time",
		create_time: "1 hour ago",
	},
	{
		id: 10,
		image: "test image",
		name: "Software Engineer",
		author: "SaveNet inc",
		location: "London",
		amount: "$12,000",
		type: "Full Time",
		create_time: "1 hour ago",
	},
];
